// <auto-generated/>
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Windows;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("LoStar")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("LoStar")]
[assembly: AssemblyCopyright("Copyright ©  2015")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

//In order to begin building localizable applications, set 
//<UICulture>CultureYouAreCodingWith</UICulture> in your .csproj file
//inside a <PropertyGroup>.  For example, if you are using US english
//in your source files, set the <UICulture> to en-US.  Then uncomment
//the NeutralResourceLanguage attribute below.  Update the "en-US" in
//the line below to match the UICulture setting in the project file.

//[assembly: NeutralResourcesLanguage("en-US", UltimateResourceFallbackLocation.Satellite)]


[assembly: ThemeInfo(
    ResourceDictionaryLocation.None, //where theme specific resource dictionaries are located
    //(used if a resource is not found in the page, 
    // or application resource dictionaries)
    ResourceDictionaryLocation.SourceAssembly //where the generic resource dictionary is located
    //(used if a resource is not found in the page, 
    // app, or any theme specific resource dictionaries)
)]


// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("0.1.*")]
[assembly: AssemblyVersion("0.1.0.428")]
[assembly: AssemblyFileVersion("0.1.0.428")]

////  "0.1.0.428"  Compiled 06.01.2016 11:09
//// Refactored TimeLine property from Stripe to DigitalStripe

////  "0.1.0.427"  Compiled 06.01.2016 10:27
////  "0.1.0.426"  Compiled 06.01.2016 10:26
////  "0.1.0.425"  Compiled 06.01.2016 10:25
////  "0.1.0.424"  Compiled 06.01.2016 10:25
////  "0.1.0.423"  Compiled 06.01.2016 10:17
////  "0.1.0.422"  Compiled 06.01.2016 10:15
////  "0.1.0.421"  Compiled 06.01.2016 10:14
////  "0.1.0.420"  Compiled 06.01.2016 10:13
////  "0.1.0.419"  Compiled 06.01.2016 10:12
//// Implemented ZoomInMax

////  "0.1.0.418"  Compiled 05.01.2016 22:35
////  "0.1.0.417"  Compiled 05.01.2016 22:29
////  "0.1.0.416"  Compiled 05.01.2016 22:29
////  "0.1.0.415"  Compiled 05.01.2016 22:21
////  "0.1.0.414"  Compiled 05.01.2016 22:20
////  "0.1.0.413"  Compiled 05.01.2016 22:19
////  "0.1.0.412"  Compiled 05.01.2016 22:17
////  "0.1.0.411"  Compiled 05.01.2016 22:08
////  "0.1.0.410"  Compiled 05.01.2016 22:07
////  "0.1.0.409"  Compiled 05.01.2016 21:48
////  "0.1.0.408"  Compiled 05.01.2016 21:41
//// Inserted IBrowsableTimeline.
//// Previous following event
//// 

////  "0.1.0.407"  Compiled 05.01.2016 21:39
////  "0.1.0.406"  Compiled 05.01.2016 21:34
////  "0.1.0.405"  Compiled 05.01.2016 21:14
////  "0.1.0.404"  Compiled 05.01.2016 20:57
////  "0.1.0.403"  Compiled 05.01.2016 20:55
////  "0.1.0.402"  Compiled 05.01.2016 20:53
////  "0.1.0.401"  Compiled 05.01.2016 20:44
////  "0.1.0.400"  Compiled 05.01.2016 20:43
////  "0.1.0.399"  Compiled 05.01.2016 20:31
////  "0.1.0.398"  Compiled 05.01.2016 20:21
////  "0.1.0.397"  Compiled 05.01.2016 20:17
////  "0.1.0.396"  Compiled 05.01.2016 19:55
////  "0.1.0.395"  Compiled 05.01.2016 19:53
////  "0.1.0.394"  Compiled 05.01.2016 19:53
////  "0.1.0.393"  Compiled 05.01.2016 19:52
////  "0.1.0.392"  Compiled 05.01.2016 19:51
////  "0.1.0.391"  Compiled 05.01.2016 19:45
//// Added previous or following transition

////  "0.1.0.390"  Compiled 05.01.2016 19:06
////  "0.1.0.389"  Compiled 05.01.2016 19:01
////  "0.1.0.388"  Compiled 05.01.2016 19:01
////  "0.1.0.387"  Compiled 05.01.2016 18:59
//// Added the SelectableStripe in the class hierarchy.

////  "0.1.0.386"  Compiled 05.01.2016 17:52
////  "0.1.0.385"  Compiled 05.01.2016 17:51
////  "0.1.0.384"  Compiled 05.01.2016 17:49
////  "0.1.0.383"  Compiled 05.01.2016 17:49
////  "0.1.0.382"  Compiled 05.01.2016 17:46
////  "0.1.0.381"  Compiled 05.01.2016 17:45
////  "0.1.0.380"  Compiled 05.01.2016 17:45
////  "0.1.0.379"  Compiled 05.01.2016 17:31
////  "0.1.0.378"  Compiled 05.01.2016 17:30
////  "0.1.0.377"  Compiled 05.01.2016 17:24
////  "0.1.0.376"  Compiled 05.01.2016 17:16
////  "0.1.0.375"  Compiled 05.01.2016 17:15
////  "0.1.0.374"  Compiled 05.01.2016 17:11
////  "0.1.0.373"  Compiled 05.01.2016 17:10
////  "0.1.0.372"  Compiled 05.01.2016 17:10
////  "0.1.0.371"  Compiled 05.01.2016 17:07
////  "0.1.0.370"  Compiled 05.01.2016 17:06
////  "0.1.0.369"  Compiled 05.01.2016 17:02
////  "0.1.0.368"  Compiled 05.01.2016 16:56
////  "0.1.0.367"  Compiled 05.01.2016 16:54
////  "0.1.0.366"  Compiled 05.01.2016 16:48
////  "0.1.0.365"  Compiled 05.01.2016 16:26
////  "0.1.0.364"  Compiled 05.01.2016 16:20
////  "0.1.0.363"  Compiled 05.01.2016 16:17
////  "0.1.0.362"  Compiled 05.01.2016 16:17
////  "0.1.0.361"  Compiled 05.01.2016 16:16
////  "0.1.0.360"  Compiled 05.01.2016 16:15
////  "0.1.0.359"  Compiled 05.01.2016 16:15
////  "0.1.0.358"  Compiled 05.01.2016 15:38
////  "0.1.0.357"  Compiled 05.01.2016 15:37
////  "0.1.0.356"  Compiled 05.01.2016 15:36
////  "0.1.0.355"  Compiled 05.01.2016 15:34
////  "0.1.0.354"  Compiled 05.01.2016 15:34
////  "0.1.0.353"  Compiled 05.01.2016 15:34
////  "0.1.0.352"  Compiled 05.01.2016 15:20
////  "0.1.0.351"  Compiled 05.01.2016 15:20
////  "0.1.0.350"  Compiled 05.01.2016 15:17
////  "0.1.0.349"  Compiled 05.01.2016 15:15
////  "0.1.0.348"  Compiled 05.01.2016 15:15
////  "0.1.0.347"  Compiled 05.01.2016 15:11
////  "0.1.0.346"  Compiled 05.01.2016 15:11
////  "0.1.0.345"  Compiled 05.01.2016 15:10
////  "0.1.0.344"  Compiled 05.01.2016 15:06
////  "0.1.0.343"  Compiled 05.01.2016 15:06
////  "0.1.0.342"  Compiled 05.01.2016 15:05
////  "0.1.0.341"  Compiled 05.01.2016 15:05
////  "0.1.0.340"  Compiled 05.01.2016 15:00
////  "0.1.0.339"  Compiled 05.01.2016 14:56
////  "0.1.0.338"  Compiled 05.01.2016 14:55
////  "0.1.0.337"  Compiled 05.01.2016 14:44
////  "0.1.0.336"  Compiled 05.01.2016 14:41
////  "0.1.0.335"  Compiled 05.01.2016 14:41
////  "0.1.0.334"  Compiled 05.01.2016 14:40
////  "0.1.0.333"  Compiled 05.01.2016 14:24
////  "0.1.0.332"  Compiled 05.01.2016 14:19
////  "0.1.0.331"  Compiled 05.01.2016 14:18
////  "0.1.0.330"  Compiled 05.01.2016 14:14
////  "0.1.0.329"  Compiled 05.01.2016 14:12
////  "0.1.0.328"  Compiled 05.01.2016 14:10
////  "0.1.0.327"  Compiled 05.01.2016 13:57
////  "0.1.0.326"  Compiled 05.01.2016 11:51
////  "0.1.0.325"  Compiled 05.01.2016 11:45
////  "0.1.0.324"  Compiled 05.01.2016 11:45
////  "0.1.0.323"  Compiled 05.01.2016 11:43
////  "0.1.0.322"  Compiled 05.01.2016 11:42
////  "0.1.0.321"  Compiled 05.01.2016 11:41
////  "0.1.0.320"  Compiled 05.01.2016 11:40
////  "0.1.0.319"  Compiled 05.01.2016 11:35
////  "0.1.0.318"  Compiled 05.01.2016 11:26
////  "0.1.0.317"  Compiled 05.01.2016 11:24
//// Added CenterCursor tool on the toolbar

////  "0.1.0.316"  Compiled 04.01.2016 12:12
////  "0.1.0.315"  Compiled 03.01.2016 18:52
////  "0.1.0.314"  Compiled 03.01.2016 18:51
////  "0.1.0.313"  Compiled 03.01.2016 18:41
////  "0.1.0.312"  Compiled 03.01.2016 18:41
////  "0.1.0.311"  Compiled 03.01.2016 18:37
////  "0.1.0.310"  Compiled 03.01.2016 18:21
//// Able to load captures from file in xml format

////  "0.1.0.309"  Compiled 03.01.2016 17:30
////  "0.1.0.308"  Compiled 03.01.2016 12:46
////  "0.1.0.307"  Compiled 03.01.2016 12:46
////  "0.1.0.306"  Compiled 03.01.2016 12:44
////  "0.1.0.305"  Compiled 03.01.2016 12:39
//// Added Cursor movement event
//// 

////  "0.1.0.304"  Compiled 03.01.2016 12:03
////  "0.1.0.303"  Compiled 03.01.2016 12:03
////  "0.1.0.302"  Compiled 03.01.2016 11:48
////  "0.1.0.301"  Compiled 03.01.2016 11:38
////  "0.1.0.300"  Compiled 03.01.2016 11:18
////  "0.1.0.299"  Compiled 03.01.2016 11:03
////  "0.1.0.298"  Compiled 03.01.2016 10:59
////  "0.1.0.297"  Compiled 03.01.2016 10:58
////  "0.1.0.296"  Compiled 03.01.2016 10:57
////  "0.1.0.295"  Compiled 03.01.2016 10:56
////  "0.1.0.294"  Compiled 03.01.2016 10:55
////  "0.1.0.293"  Compiled 02.01.2016 22:21
////  "0.1.0.292"  Compiled 02.01.2016 22:19
////  "0.1.0.291"  Compiled 02.01.2016 22:19
////  "0.1.0.290"  Compiled 02.01.2016 22:19
////  "0.1.0.289"  Compiled 02.01.2016 22:18
////  "0.1.0.288"  Compiled 02.01.2016 22:15
////  "0.1.0.287"  Compiled 02.01.2016 22:13
////  "0.1.0.286"  Compiled 02.01.2016 22:10
////  "0.1.0.285"  Compiled 02.01.2016 22:07
////  "0.1.0.284"  Compiled 02.01.2016 22:04
////  "0.1.0.283"  Compiled 02.01.2016 22:03
////  "0.1.0.282"  Compiled 02.01.2016 22:00
////  "0.1.0.281"  Compiled 02.01.2016 21:55
////  "0.1.0.280"  Compiled 02.01.2016 21:28
////  "0.1.0.279"  Compiled 02.01.2016 21:24
//// Implemented all blends of zoom

////  "0.1.0.278"  Compiled 02.01.2016 21:22
////  "0.1.0.277"  Compiled 02.01.2016 21:19
////  "0.1.0.276"  Compiled 02.01.2016 21:18
////  "0.1.0.275"  Compiled 02.01.2016 21:18
////  "0.1.0.274"  Compiled 02.01.2016 21:16
////  "0.1.0.273"  Compiled 02.01.2016 21:02
////  "0.1.0.272"  Compiled 02.01.2016 21:01
////  "0.1.0.271"  Compiled 02.01.2016 21:00
////  "0.1.0.270"  Compiled 02.01.2016 20:46
////  "0.1.0.269"  Compiled 02.01.2016 18:39
////  "0.1.0.268"  Compiled 02.01.2016 18:17
////  "0.1.0.267"  Compiled 02.01.2016 17:42
////  "0.1.0.266"  Compiled 02.01.2016 17:42
////  "0.1.0.265"  Compiled 02.01.2016 17:41
////  "0.1.0.264"  Compiled 02.01.2016 17:40
////  "0.1.0.263"  Compiled 02.01.2016 17:38
////  "0.1.0.262"  Compiled 02.01.2016 17:36
////  "0.1.0.261"  Compiled 02.01.2016 16:55
////  "0.1.0.260"  Compiled 02.01.2016 16:53
////  "0.1.0.259"  Compiled 02.01.2016 16:48
////  "0.1.0.258"  Compiled 02.01.2016 16:47
//// Refactored TimeCursor from CursorOverlay to draw the cursor (s)

////  "0.1.0.257"  Compiled 02.01.2016 15:05
//// Added Global timeline widget on top of CursorOverlay

////  "0.1.0.256"  Compiled 02.01.2016 14:20
////  "0.1.0.255"  Compiled 02.01.2016 13:51
////  "0.1.0.254"  Compiled 02.01.2016 13:51
////  "0.1.0.253"  Compiled 02.01.2016 13:48
//// CursorOverlay has a top row containing the whole time span

////  "0.1.0.252"  Compiled 01.01.2016 21:40
////  "0.1.0.251"  Compiled 01.01.2016 21:39
////  "0.1.0.250"  Compiled 01.01.2016 21:37
////  "0.1.0.249"  Compiled 01.01.2016 21:36
////  "0.1.0.248"  Compiled 01.01.2016 21:31
////  "0.1.0.247"  Compiled 01.01.2016 21:28
////  "0.1.0.246"  Compiled 01.01.2016 21:26
////  "0.1.0.245"  Compiled 01.01.2016 21:21
//// Complete toolbar

////  "0.1.0.244"  Compiled 01.01.2016 19:36
////  "0.1.0.243"  Compiled 01.01.2016 19:10
////  "0.1.0.242"  Compiled 01.01.2016 19:05
////  "0.1.0.241"  Compiled 01.01.2016 18:44
//// Implemented standard WPF toolbar

////  "0.1.0.240"  Compiled 01.01.2016 18:02
////  "0.1.0.239"  Compiled 01.01.2016 18:01
////  "0.1.0.238"  Compiled 22.12.2015 17:44
////  "0.1.0.237"  Compiled 20.12.2015 20:37
////  "0.1.0.236"  Compiled 20.12.2015 20:34
////  "0.1.0.235"  Compiled 20.12.2015 20:32
////  "0.1.0.234"  Compiled 20.12.2015 20:28
////  "0.1.0.233"  Compiled 20.12.2015 20:25
////  "0.1.0.232"  Compiled 19.12.2015 20:22
//// Added toolbox

////  "0.1.0.231"  Compiled 19.12.2015 16:55
////  "0.1.0.230"  Compiled 19.12.2015 16:55
////  "0.1.0.229"  Compiled 19.12.2015 16:55
////  "0.1.0.228"  Compiled 19.12.2015 16:52
////  "0.1.0.227"  Compiled 19.12.2015 16:49
////  "0.1.0.226"  Compiled 19.12.2015 15:27
////  "0.1.0.225"  Compiled 19.12.2015 15:25
////  "0.1.0.224"  Compiled 19.12.2015 15:25
////  "0.1.0.223"  Compiled 19.12.2015 15:24
////  "0.1.0.222"  Compiled 19.12.2015 15:23
////  "0.1.0.221"  Compiled 19.12.2015 15:20
////  "0.1.0.220"  Compiled 19.12.2015 14:15
////  "0.1.0.219"  Compiled 19.12.2015 14:13
////  "0.1.0.218"  Compiled 19.12.2015 13:59
////  "0.1.0.217"  Compiled 19.12.2015 13:57
////  "0.1.0.216"  Compiled 19.12.2015 13:54
////  "0.1.0.215"  Compiled 19.12.2015 13:48
////  "0.1.0.214"  Compiled 19.12.2015 13:47
////  "0.1.0.213"  Compiled 19.12.2015 13:45
////  "0.1.0.212"  Compiled 19.12.2015 13:45
////  "0.1.0.211"  Compiled 19.12.2015 13:44
////  "0.1.0.210"  Compiled 19.12.2015 10:30
////  "0.1.0.209"  Compiled 18.12.2015 21:06
////  "0.1.0.208"  Compiled 18.12.2015 21:05
////  "0.1.0.207"  Compiled 18.12.2015 21:05
////  "0.1.0.206"  Compiled 18.12.2015 21:04
////  "0.1.0.205"  Compiled 18.12.2015 21:02
////  "0.1.0.204"  Compiled 18.12.2015 21:02
////  "0.1.0.203"  Compiled 18.12.2015 21:01
//// The Window adapts itself to the Window Size

////  "0.1.0.202"  Compiled 18.12.2015 21:00
////  "0.1.0.201"  Compiled 18.12.2015 20:59
//// Added SizeChanged event handler

////  "0.1.0.200"  Compiled 18.12.2015 20:57
////  "0.1.0.199"  Compiled 18.12.2015 20:45
//// Added MouseMove element

////  "0.1.0.198"  Compiled 18.12.2015 20:44
////  "0.1.0.197"  Compiled 18.12.2015 20:42
////  "0.1.0.196"  Compiled 18.12.2015 20:41
////  "0.1.0.195"  Compiled 18.12.2015 20:40
////  "0.1.0.194"  Compiled 18.12.2015 20:40
////  "0.1.0.193"  Compiled 18.12.2015 20:39
////  "0.1.0.192"  Compiled 18.12.2015 20:36
////  "0.1.0.191"  Compiled 18.12.2015 20:28
////  "0.1.0.190"  Compiled 18.12.2015 20:21
////  "0.1.0.189"  Compiled 18.12.2015 20:21
////  "0.1.0.188"  Compiled 18.12.2015 20:18
////  "0.1.0.187"  Compiled 18.12.2015 20:16
//// Added MouseDown event to the stripe container

////  "0.1.0.186"  Compiled 18.12.2015 20:15
////  "0.1.0.185"  Compiled 18.12.2015 20:14
////  "0.1.0.184"  Compiled 18.12.2015 19:47
////  "0.1.0.183"  Compiled 18.12.2015 19:47
////  "0.1.0.182"  Compiled 18.12.2015 18:51
////  "0.1.0.181"  Compiled 18.12.2015 18:50
////  "0.1.0.180"  Compiled 18.12.2015 18:46
////  "0.1.0.179"  Compiled 18.12.2015 18:46
////  "0.1.0.178"  Compiled 18.12.2015 18:46
////  "0.1.0.177"  Compiled 18.12.2015 18:36
////  "0.1.0.176"  Compiled 18.12.2015 18:36
////  "0.1.0.175"  Compiled 18.12.2015 18:36
////  "0.1.0.174"  Compiled 18.12.2015 18:35
////  "0.1.0.173"  Compiled 18.12.2015 18:32
////  "0.1.0.172"  Compiled 18.12.2015 18:32
////  "0.1.0.171"  Compiled 18.12.2015 18:30
////  "0.1.0.170"  Compiled 18.12.2015 18:30
////  "0.1.0.169"  Compiled 18.12.2015 18:29
////  "0.1.0.168"  Compiled 18.12.2015 18:28
////  "0.1.0.167"  Compiled 18.12.2015 18:26
////  "0.1.0.166"  Compiled 18.12.2015 18:19
////  "0.1.0.165"  Compiled 18.12.2015 18:18
////  "0.1.0.164"  Compiled 18.12.2015 18:08
////  "0.1.0.163"  Compiled 18.12.2015 18:06
////  "0.1.0.162"  Compiled 18.12.2015 11:58
////  "0.1.0.161"  Compiled 18.12.2015 11:58
////  "0.1.0.160"  Compiled 18.12.2015 11:57
//// Added Mouse manipulation in CursorOverlay

////  "0.1.0.159"  Compiled 17.12.2015 21:55
////  "0.1.0.158"  Compiled 17.12.2015 21:55
////  "0.1.0.157"  Compiled 17.12.2015 21:54
////  "0.1.0.156"  Compiled 17.12.2015 21:54
////  "0.1.0.155"  Compiled 17.12.2015 21:50
////  "0.1.0.154"  Compiled 17.12.2015 21:47
////  "0.1.0.153"  Compiled 17.12.2015 21:45
////  "0.1.0.152"  Compiled 17.12.2015 21:44
////  "0.1.0.151"  Compiled 17.12.2015 21:43
//// Added multiple cursor support

////  "0.1.0.150"  Compiled 17.12.2015 21:36
////  "0.1.0.149"  Compiled 17.12.2015 21:35
////  "0.1.0.148"  Compiled 17.12.2015 21:34
////  "0.1.0.147"  Compiled 17.12.2015 21:33
////  "0.1.0.146"  Compiled 17.12.2015 21:33
////  "0.1.0.145"  Compiled 17.12.2015 21:31
////  "0.1.0.144"  Compiled 17.12.2015 21:30
////  "0.1.0.143"  Compiled 17.12.2015 21:29
//// Added CursorOverlay cursor widget

////  "0.1.0.142"  Compiled 17.12.2015 21:06
//// Added Superimposed cavas to show the cursor

////  "0.1.0.141"  Compiled 17.12.2015 20:57
//// Centered numbers on TimeAxisStrip and added vertical ticks

////  "0.1.0.140"  Compiled 17.12.2015 20:15
////  "0.1.0.139"  Compiled 17.12.2015 20:14
////  "0.1.0.138"  Compiled 17.12.2015 20:09
////  "0.1.0.137"  Compiled 17.12.2015 20:08
////  "0.1.0.136"  Compiled 17.12.2015 20:04
////  "0.1.0.135"  Compiled 17.12.2015 20:03
////  "0.1.0.134"  Compiled 17.12.2015 20:01
////  "0.1.0.133"  Compiled 17.12.2015 20:01
////  "0.1.0.132"  Compiled 17.12.2015 19:54
//// Added tolerance on minimum tick distance (AxisTickGenerator)

////  "0.1.0.131"  Compiled 16.12.2015 09:06
////  "0.1.0.130"  Compiled 16.12.2015 09:04
////  "0.1.0.129"  Compiled 16.12.2015 09:03
////  "0.1.0.128"  Compiled 16.12.2015 09:00
////  "0.1.0.127"  Compiled 16.12.2015 08:58
////  "0.1.0.126"  Compiled 16.12.2015 08:57
////  "0.1.0.125"  Compiled 16.12.2015 08:57
////  "0.1.0.124"  Compiled 16.12.2015 08:54
////  "0.1.0.123"  Compiled 16.12.2015 08:51
////  "0.1.0.122"  Compiled 16.12.2015 08:49
////  "0.1.0.121"  Compiled 16.12.2015 08:43
////  "0.1.0.120"  Compiled 16.12.2015 08:41
////  "0.1.0.119"  Compiled 16.12.2015 08:40
////  "0.1.0.118"  Compiled 16.12.2015 08:40
////  "0.1.0.117"  Compiled 16.12.2015 08:39
////  "0.1.0.116"  Compiled 16.12.2015 08:38
////  "0.1.0.115"  Compiled 16.12.2015 08:37
////  "0.1.0.114"  Compiled 16.12.2015 08:37
////  "0.1.0.113"  Compiled 16.12.2015 08:37
////  "0.1.0.112"  Compiled 16.12.2015 08:34
////  "0.1.0.111"  Compiled 16.12.2015 08:34
////  "0.1.0.110"  Compiled 16.12.2015 08:29
////  "0.1.0.109"  Compiled 16.12.2015 08:28
////  "0.1.0.108"  Compiled 16.12.2015 08:28
//// Added TimeAxisStripe widget

////  "0.1.0.107"  Compiled 16.12.2015 08:24
////  "0.1.0.106"  Compiled 16.12.2015 08:22
////  "0.1.0.105"  Compiled 16.12.2015 08:21
////  "0.1.0.104"  Compiled 16.12.2015 08:20
////  "0.1.0.103"  Compiled 16.12.2015 08:19
////  "0.1.0.102"  Compiled 16.12.2015 08:17
////  "0.1.0.101"  Compiled 16.12.2015 08:15
////  "0.1.0.100"  Compiled 16.12.2015 08:09
////  "0.1.0.99"  Compiled 16.12.2015 08:07
////  "0.1.0.98"  Compiled 15.12.2015 23:44
////  "0.1.0.97"  Compiled 15.12.2015 23:39
////  "0.1.0.96"  Compiled 15.12.2015 23:38
////  "0.1.0.95"  Compiled 15.12.2015 23:38
////  "0.1.0.94"  Compiled 15.12.2015 23:37
////  "0.1.0.93"  Compiled 15.12.2015 23:36
////  "0.1.0.92"  Compiled 15.12.2015 23:35
////  "0.1.0.91"  Compiled 15.12.2015 23:34
////  "0.1.0.90"  Compiled 15.12.2015 22:32
////  "0.1.0.89"  Compiled 15.12.2015 22:32
////  "0.1.0.88"  Compiled 15.12.2015 22:15
////  "0.1.0.87"  Compiled 15.12.2015 22:11
////  "0.1.0.86"  Compiled 15.12.2015 22:09
////  "0.1.0.85"  Compiled 15.12.2015 22:08
////  "0.1.0.84"  Compiled 15.12.2015 22:07
////  "0.1.0.83"  Compiled 15.12.2015 22:05
////  "0.1.0.82"  Compiled 15.12.2015 21:51
////  "0.1.0.81"  Compiled 15.12.2015 21:47
////  "0.1.0.80"  Compiled 15.12.2015 21:46
////  "0.1.0.79"  Compiled 15.12.2015 21:17
//// Added Zoom event to DigitalStripe.

////  "0.1.0.78"  Compiled 15.12.2015 20:58
////  "0.1.0.77"  Compiled 15.12.2015 20:57
////  "0.1.0.76"  Compiled 15.12.2015 20:55
////  "0.1.0.75"  Compiled 15.12.2015 20:54
////  "0.1.0.74"  Compiled 15.12.2015 20:53
////  "0.1.0.73"  Compiled 15.12.2015 20:53
////  "0.1.0.72"  Compiled 15.12.2015 20:46
////  "0.1.0.71"  Compiled 15.12.2015 20:42
////  "0.1.0.70"  Compiled 15.12.2015 20:41
////  "0.1.0.69"  Compiled 15.12.2015 20:24
////  "0.1.0.68"  Compiled 15.12.2015 11:19
//// Added ITimelineSegment interface to disseminate zoom events

////  "0.1.0.67"  Compiled 15.12.2015 08:32
////  "0.1.0.66"  Compiled 15.12.2015 08:31
////  "0.1.0.65"  Compiled 15.12.2015 08:29
////  "0.1.0.64"  Compiled 15.12.2015 08:28
////  "0.1.0.63"  Compiled 15.12.2015 08:27
////  "0.1.0.62"  Compiled 15.12.2015 08:24
////  "0.1.0.61"  Compiled 15.12.2015 08:24
////  "0.1.0.60"  Compiled 15.12.2015 08:23
////  "0.1.0.59"  Compiled 15.12.2015 08:07
////  "0.1.0.58"  Compiled 15.12.2015 08:07
////  "0.1.0.57"  Compiled 15.12.2015 08:06
////  "0.1.0.56"  Compiled 15.12.2015 08:06
////  "0.1.0.55"  Compiled 15.12.2015 08:04
////  "0.1.0.54"  Compiled 15.12.2015 08:03
////  "0.1.0.53"  Compiled 15.12.2015 07:59
//// Corrected DigitalTimeline.ForEach

////  "0.1.0.52"  Compiled 15.12.2015 07:56
////  "0.1.0.51"  Compiled 15.12.2015 07:32
////  "0.1.0.50"  Compiled 15.12.2015 07:29
////  "0.1.0.49"  Compiled 15.12.2015 07:29
////  "0.1.0.48"  Compiled 15.12.2015 06:41
////  "0.1.0.47"  Compiled 14.12.2015 22:53
////  "0.1.0.46"  Compiled 14.12.2015 22:52
////  "0.1.0.45"  Compiled 14.12.2015 22:51
////  "0.1.0.44"  Compiled 14.12.2015 22:50
////  "0.1.0.43"  Compiled 14.12.2015 22:49
////  "0.1.0.42"  Compiled 14.12.2015 22:49
////  "0.1.0.41"  Compiled 14.12.2015 22:46
////  "0.1.0.40"  Compiled 14.12.2015 22:45
////  "0.1.0.39"  Compiled 14.12.2015 22:43
////  "0.1.0.38"  Compiled 14.12.2015 22:42
////  "0.1.0.37"  Compiled 14.12.2015 22:42
////  "0.1.0.36"  Compiled 14.12.2015 22:41
////  "0.1.0.35"  Compiled 14.12.2015 22:40
////  "0.1.0.34"  Compiled 14.12.2015 22:39
////  "0.1.0.33"  Compiled 14.12.2015 22:34
////  "0.1.0.32"  Compiled 14.12.2015 22:33
////  "0.1.0.31"  Compiled 14.12.2015 22:30
////  "0.1.0.30"  Compiled 14.12.2015 22:23
////  "0.1.0.29"  Compiled 14.12.2015 22:17
////  "0.1.0.28"  Compiled 14.12.2015 22:16
////  "0.1.0.27"  Compiled 14.12.2015 22:15
////  "0.1.0.26"  Compiled 14.12.2015 22:14
////  "0.1.0.25"  Compiled 14.12.2015 22:14
////  "0.1.0.24"  Compiled 14.12.2015 22:09
////  "0.1.0.23"  Compiled 14.12.2015 22:05
////  "0.1.0.22"  Compiled 14.12.2015 22:03
////  "0.1.0.21"  Compiled 14.12.2015 22:03
////  "0.1.0.20"  Compiled 14.12.2015 22:02
////  "0.1.0.19"  Compiled 14.12.2015 22:01
//// First displaied waveforms in WPF

////  "0.1.0.18"  Compiled 14.12.2015 22:00
////  "0.1.0.17"  Compiled 14.12.2015 21:55
////  "0.1.0.16"  Compiled 14.12.2015 21:54
////  "0.1.0.15"  Compiled 14.12.2015 20:59
////  "0.1.0.14"  Compiled 14.12.2015 20:51
////  "0.1.0.13"  Compiled 14.12.2015 20:44
////  "0.1.0.12"  Compiled 14.12.2015 19:29
////  "0.1.0.11"  Compiled 14.12.2015 19:28
////  "0.1.0.10"  Compiled 14.12.2015 19:27
////  "0.1.0.9"  Compiled 14.12.2015 19:22
////  "0.1.0.8"  Compiled 14.12.2015 19:21
////  "0.1.0.7"  Compiled 14.12.2015 19:14
////  "0.1.0.6"  Compiled 14.12.2015 19:13
////  "0.1.0.5"  Compiled 14.12.2015 19:05
////  "0.1.0.4"  Compiled 14.12.2015 19:04
////  "0.1.0.3"  Compiled 13.12.2015 21:36
////  "0.1.0.2"  Compiled 13.12.2015 21:35
////  "0.1.0.1"  Compiled 13.12.2015 21:34
//// First gitted version.
//// DigitalTimelineTest finished and passed
//// 
